import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];p=json.loads((R/'data/tiantan-corridor-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text());x,y=p['center'];s={'id':'tiantan-corridor','name':'天坛七十二长廊','subject':'绿瓦步廊与七十二间梁架','parentPlace':'tiantan','methodLabel':'实景参考重建','x':x,'y':y,'rotation':0,'bounds':p['bounds'],'maskPolygon':p['maskPolygon'],'osmId':p['osmId'],'span':2.15,'height':.052,'groundHeight':.012,'viewOffset':[60,100,160],'author':'参考摄影：钉钉；建筑重建：本项目','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'https://commons.wikimedia.org/wiki/File:72_Long_Corridor,_Temple_of_Heaven.jpg','method':'保留 OSM 曲折轴线，按天坛官方宽5米、72间资料与实景照片重建绿瓦、红柱、梁架、坐凳和部分后墙。轴线约289米，官网记载295米；屋顶高度、柱位、后墙范围及彩绘细节为推定，非测绘模型，未将照片用作贴图。','detailView':{'label':'走近长廊梁架','x':(p['axis'][2][0]+p['axis'][3][0])/2,'y':(p['axis'][2][1]+p['axis'][3][1])/2,'height':.03,'span':.125,'offset':[.15,.32,1.8]},'contextView':{'label':'查看长廊全貌','x':x,'y':y,'height':.025,'span':2.15,'offset':[60,100,160]},'relatedModels':[{'id':'tiantan','label':'查看祈年殿'}],'lods':{}}
for level in ['preview','detail']:
 a=json.loads((R/f'output/tiantan-corridor/{level}.json').read_text());s['lods'][level]=f'public/assets/tiantan-corridor/{level}.glb?v={a["revision"]}'
m['assets']=[a for a in m['assets']if a['id']!=s['id']]+[s]
for a in m['assets']:
 if a['id']=='tiantan':a['relatedModels']=[q for q in a.get('relatedModels',[])if q['id']!=s['id']]+[{'id':s['id'],'label':'查看七十二长廊'}]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2))
f=R/'index.html';s=f.read_text().replace('20260930-facades1','20260930-corridor1');note='<h3>天坛七十二长廊</h3><p>绿瓦、红柱与开放步廊按实景参考重建，柱距及装饰细节为推定。<a href="public/assets/tiantan-corridor/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in s:s=s.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(s)
(R/'public/assets/tiantan-corridor/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>七十二长廊模型来源</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:18px/1.8 system-ui;color:#213a32}</style><h1>天坛七十二长廊 · 实景参考重建</h1><p><a href="https://tiantanpark.cn/scenic_spot_list/detail/959.html">天坛官网《长廊》</a>记载295米长、5米宽、72间；<a href="https://gygl.beijing.gov.cn/mlgy/mlgy_gyjg01/201912/t20191211_1048291.html">北京市公园管理中心《长廊》</a>记载曲尺形，修复时撤除槛墙、安置坐凳。部分早期旅游资料记为350米，本模型保留OSM地图约289米的轴线，不放大地图来凑长度。</p><p>参考摄影：© 钉钉 / Wikimedia Commons，<a href="https://commons.wikimedia.org/wiki/File:72_Long_Corridor,_Temple_of_Heaven.jpg">72 Long Corridor, Temple of Heaven.jpg</a>，<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。仅参考建筑外观，未使用照片像素作贴图。本项目新建模型同样按 CC BY-SA 4.0 提供。</p><p>位置和轴线：© OpenStreetMap contributors，ODbL。宽度参考官网5米；72间按地理轴线各段长度分配，并非实测柱位。檐口、屋脊高度、后墙范围、坐凳、瓦片和装饰彩绘为推定。模型用于旅游地图，非测绘或摄影测量成果。两级精度分别按视距加载。</p></html>''')
