import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];p=json.loads((R/'data/circular-mound-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text());x,y=p['center']
s={'id':'circular-mound','name':'圜丘坛','subject':'三层汉白玉坛台、九级台阶与内圆外方院落','parentPlace':'tiantan','methodLabel':'资料与实景参考重建','x':x,'y':y,'rotation':0,'bounds':p['bounds'],'sourceOsmIds':p['sourceOsmIds'],'maskPolygons':p['maskPolygons'],'plantingPolygon':p['court'],'span':1.82,'height':.066,'groundHeight':.012,'viewOffset':[30,110,150],'author':'参考摄影：BrokenSphere；建筑重建：本项目','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'public/assets/circular-mound/ATTRIBUTION.html','method':'三层直径与高度、九级台阶和九重铺石按北京市公园管理中心资料；院墙与门位置沿用 OSM。雕刻、栏板与石材纹理为参考重建，非测绘扫描。','detailView':{'label':'走近坛台与石栏','x':x,'y':y,'height':.035,'span':.36,'offset':[.22,.52,.82]},'contextView':{'label':'圜丘坛完整院落','x':x,'y':y,'height':.035,'span':1.85,'offset':[35,110,155]},'relatedModels':[{'id':'imperial-vault','label':'查看皇穹宇'},{'id':'echo-court','label':'查看回音壁院落'},{'id':'mound-outer-gate','label':'查看棂星门'}],'lods':{}}
for level in ['preview','detail']:
 a=json.loads((R/f'output/circular-mound/{level}.json').read_text());s['lods'][level]=f'public/assets/circular-mound/{level}.glb?v={a["revision"]}'
m['assets']=[a for a in m['assets']if a['id']!=s['id']]+[s]
for a in m['assets']:
 if a['id']in ['tiantan','imperial-vault','echo-court','chengzhen','mound-inner-gate','mound-outer-gate']:a['relatedModels']=[q for q in a.get('relatedModels',[])if q['id']!='circular-mound']+[{'id':'circular-mound','label':'查看圜丘坛'}]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2))
f=R/'index.html';t=f.read_text().replace('20260930-tgates1','20260930-mound1');note='<h3>圜丘坛与院落</h3><p>三层坛台、四向九级台阶与内圆外方院落。<a href="public/assets/circular-mound/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in t:t=t.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(t)
(R/'public/assets/circular-mound/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>圜丘坛 · 来源与精度</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:18px/1.8 system-ui;color:#213a32}</style><h1>圜丘坛 · 资料与实景参考重建</h1><p>本模型包含三层坛台、四向台阶、石栏、天心石、环形铺石、圆形内壝、方形外壝与六组棂星门。北面两组棂星门沿用独立细节模型。</p><p>三层直径23.65、39.31、54.91米，高1.87、1.63、1.67米，总高5.17米，以及各层四向九级台阶、上中下层405、1134、1863块铺石，依据<a href="https://gygl.beijing.gov.cn/mlgy/mlgy_gyjg01/201912/t20191211_1048232.html">北京市公园管理中心《圜丘》</a>。9重铺石的规律亦见<a href="https://gygl.beijing.gov.cn/whgy/whgy_wsgc/201912/t20191206_885626.html">圜丘坛建筑群的主体之圜丘</a>。</p><p>院墙高度参考<a href="https://wwj.beijing.gov.cn/bjww/362760/362770/436348561/">北京市文物局《北京天坛圜丘坛建筑尺度研究》</a>，内墙1.89米、外墙2.75米。该文总高5.71米与分层高度之和不一致，本项目采用公园管理中心5.17米。墙体和门的位置保留 © OpenStreetMap contributors / ODbL 的地图数据，未强行按文献周长重缩放。</p><p>照片形制参考：© BrokenSphere / Wikimedia Commons，<a href="https://commons.wikimedia.org/wiki/File:Circular_Mound_Altar_gate_1.JPG">Circular Mound Altar gate1</a>与<a href="https://commons.wikimedia.org/wiki/File:Circular_Mound_Altar_gate_2.JPG">gate2</a>，<a href="https://creativecommons.org/licenses/by/3.0/">CC BY3.0</a>。照片未用作贴图。新模型按 CC BY-SA4.0提供。</p><p>局部石栏、柱头、螭首和莲纹采用代表性简化结构；铺石色差、院地与石材纹理来自项目既有素材，不是文物逐块摄影测量。台阶踏步宽度和栏板形制为推定，模型不代表实时开放状态。保留真实地图位置，建筑不用于施工或文保测量。</p></html>''')
print('Integrated circular-mound; assets',len(m['assets']))
