import json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];p=json.loads((R/'data/wumen-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text());s={'id':'wumen','name':'午门','subject':'五凤楼与雁翅楼','parentPlace':'forbidden','methodLabel':'实景参考重建','x':p['center'][0],'y':p['center'][1],'rotation':math.degrees(p['angle']),'bounds':p['bounds'],'span':1.95,'height':.357,'groundHeight':.012,'viewOffset':[75,90,145],'palaceReplacement':True,'sourceParts':p['sourceParts'],'author':'参考摄影：BrokenSphere；建筑重建：本项目','license':'CC BY 3.0','licenseUrl':'https://creativecommons.org/licenses/by/3.0/','source':'https://commons.wikimedia.org/wiki/File:Meridian_Gate,_Forbidden_City_center.JPG','method':'按故宫博物院资料与实景照片重建，保留 OSM 平面锚点。城台高12米，主楼面阔60.05米、进深25米；重檐庑殿顶、两翼13间廊庑、四座重檐攒尖角亭。瓦片、门洞尺寸、脊饰和彩绘为推定，非测绘或摄影测量模型。未使用照片像素作贴图。','detailView':{'label':'走近午门城楼','x':p['center'][0],'y':p['center'][1],'height':.19,'span':1.1,'offset':[.14,.7,2.4]},'contextView':{'label':'五凤楼建筑群','x':p['center'][0],'y':p['center'][1]-.37,'height':.13,'span':2.1,'offset':[75,90,145]},'relatedModels':[{'id':'duanmen','label':'查看端门城楼'},{'id':'axis-nw','label':'查看朝房细节'}],'lods':{}}
for level in ['preview','detail']:
 a=json.loads((R/f'output/wumen-detail/{level}.json').read_text());s['lods'][level]=f'public/assets/wumen-detail/{level}.glb?v={a["revision"]}'
m['assets']=[a for a in m['assets']if a['id']!='wumen']+[s]
for a in m['assets']:
 if a['id']=='duanmen':a['relatedModels']=[x for x in a.get('relatedModels',[])if x['id']!='wumen']+[{'id':'wumen','label':'查看午门五凤楼'}]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2))
f=R/'index.html';t=f.read_text().replace('20260930-axis-courts1','20260930-wumen1');note='<h3>午门 · 五凤楼</h3><p>依据故宫博物院资料与实景照片重建主楼、雁翅楼及四座角亭，保留 OSM 地理位置。瓦片、门洞和装饰细节为推定。<a href="public/assets/wumen-detail/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in t:t=t.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(t)
(R/'public/assets/wumen-detail/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>午门模型来源与精度说明</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:18px/1.8 system-ui;color:#213a32}</style><h1>午门 · 实景参考重建</h1><p>主楼重檐庑殿顶、九开间、两翼十三间廊庑、四座重檐攒尖顶方亭；城台12米，主楼面阔60.05米、进深25米，依据<a href="https://www.dpm.org.cn/explore/building/236454.html">故宫博物院《午门》</a>。总高约35.6米参考故宫博物院藏论文。</p><p>实景参考：© BrokenSphere / Wikimedia Commons，<a href="https://commons.wikimedia.org/wiki/File:Meridian_Gate,_Forbidden_City_center.JPG">Meridian Gate, Forbidden City center.JPG</a>，<a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>。仅用于结构与颜色观察，未把照片像素用于模型贴图。</p><p>位置及平面：© OpenStreetMap contributors，ODbL。本项目 Blender 重建模型按 CC BY 3.0 提供。装饰彩绘使用项目现有的代表性古建材质，不宣称与午门现存彩绘逐笔对应。</p><p>这是供旅游地图使用的照片参考模型，并非激光扫描、摄影测量或文保测绘成果。柱距、廊楼高度、门洞尺寸、脊饰、栏杆与瓦片间距属于推定。保留两级几何精度，减少城市全景加载成本。</p></html>''')
