import json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];plan=json.loads((R/'data/tiantan-gates-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text())
for p in plan['parts']:
 x,y=p['center'];hall=p['kind']=='hall';s={'id':p['id'],'name':p['name'],'subject':'绿瓦歇山顶与三道拱券'if hall else'汉白玉石柱、宝顶与云纹饰件','parentPlace':'tiantan','methodLabel':'实景参考重建','x':x,'y':y,'rotation':math.degrees(p['angle']),'bounds':p['bounds'],'osmId':p['osmId'],'maskPolygon':p['maskPolygon'],'plantingBounds':[x-.21,y-.14,x+.21,y+.14],'span':.32 if hall else .27,'height':.115 if hall else .054,'groundHeight':.012,'viewOffset':[25,80,160],'author':'参考摄影：Bjoertvedt、MiiCii、BrokenSphere；建筑重建：本项目','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'public/assets/tiantan-gates/ATTRIBUTION.html','method':'根据实景照片重建，保留 OpenStreetMap 地理位置和占地。高度、门洞比例、云纹、斗拱与彩画为推定，非测绘模型。','detailView':{'label':'走近门额与拱券'if hall else'走近石柱云纹','x':x,'y':y-(.035 if hall else .01),'height':.051 if hall else .03,'span':.23 if hall else .18,'offset':[.015,.05,.20]},'contextView':{'label':'天坛南部建筑群','x':-6.91,'y':-42.40,'height':.065,'span':2.35,'offset':[35,110,155]},'relatedModels':[{'id':'imperial-vault','label':'查看皇穹宇'},{'id':'echo-court','label':'查看回音壁院落'}]+[{'id':q['id'],'label':'查看'+q['name']}for q in plan['parts']if q['id']!=p['id']],'lods':{}}
 for level in ['preview','detail']:
  a=json.loads((R/f'output/tiantan-gates/{p["id"]}-{level}.json').read_text());s['lods'][level]=f'public/assets/tiantan-gates/{p["id"]}-{level}.glb?v={a["revision"]}'
 m['assets']=[a for a in m['assets']if a['id']!=s['id']]+[s]
for a in m['assets']:
 if a['id']in ['echo-court','imperial-vault','tiantan']:
  ids={p['id']for p in plan['parts']};a['relatedModels']=[q for q in a.get('relatedModels',[])if q['id']not in ids]+[{'id':'chengzhen','label':'查看成贞门'},{'id':'mound-outer-gate','label':'查看棂星门'}]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2))
f=R/'index.html';s=f.read_text().replace('20260930-echo1','20260930-tgates1');note='<h3>天坛成贞门与棂星门</h3><p>基于实景照片重建门殿和石柱门，保留原地图位置。<a href="public/assets/tiantan-gates/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in s:s=s.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(s)
(R/'public/assets/tiantan-gates/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>天坛门建筑 · 来源与精度</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:18px/1.8 system-ui;color:#213a32}</style><h1>成贞门与棂星门 · 实景参考重建</h1><p>三组模型分别表现成贞门门殿、圜丘外壝北棂星门、内壝北棂星门。模型位置、旋转和占地取自 © OpenStreetMap contributors（ODbL）。成贞门绿瓦歇山顶、红墙三拱券、檐下斗拱与门额，以及棂星门的六柱三门、中高侧低、宝顶和云纹轮廓参考以下照片。</p><ul><li>© Bjoertvedt，<a href="https://commons.wikimedia.org/wiki/File:Beijing_-_Temple_of_Heaven_Park_IMG_5009_Chengzhen_Gate.jpg">Chengzhen Gate, IMG 5009</a>，<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。</li><li>© MiiCii，<a href="https://commons.wikimedia.org/wiki/File:Chengzhen_Gate,_Temple_of_Heaven,_Dongcheng_District,_Beijing_(202602231349).jpg">成贞门门额，2026-02-23</a>，<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。</li><li>© BrokenSphere / Wikimedia Commons，<a href="https://commons.wikimedia.org/wiki/File:Circular_Mound_Altar_gate_1.JPG">Circular Mound Altar gate 1</a>、<a href="https://commons.wikimedia.org/wiki/File:Circular_Mound_Altar_gate_2.JPG">gate 2</a>，<a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>。</li></ul><p>照片仅作形制参考，未将其像素制成贴图。新模型按 CC BY-SA 4.0 提供。高度、石雕纹样、门洞尺寸及彩绘均为推定；彩绘与石材使用项目代表性纹理，不是扫描、摄影测量或文物逐笔还原。</p><p>外壝门采用中门关闭、两侧通行的展示状态；内壝门三门通透。门扇状态用于模型展示，不代表现场实时开放情况。详细建筑群关系可参见<a href="https://wwj.beijing.gov.cn/bjww/362760/362770/436348561/">北京市文物局《北京天坛圜丘坛建筑尺度研究》</a>。</p></html>''')
