import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];p=json.loads((R/'data/imperial-vault-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text());x,y=p['center'];bounds=[p['bounds'][0]-.002,p['bounds'][1]-.002,p['bounds'][2]+.002,p['bounds'][3]+.002]
s={'id':'imperial-vault','name':'皇穹宇','subject':'单檐蓝瓦攒尖顶与石栏台基','parentPlace':'tiantan','methodLabel':'实景参考重建','x':x,'y':y,'rotation':0,'bounds':bounds,'plantingBounds':[x-.17,y-.20,x+.17,y+.17],'span':.32,'height':.195,'groundHeight':.012,'viewOffset':[35,65,150],'author':'参考摄影：Windmemories；建筑重建：本项目','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'https://commons.wikimedia.org/wiki/File:2017-05-02_Imperial_Vault_of_Heaven.jpg','method':'按天坛官网殿台通高19.5米、殿身直径15.6米及实景照片重建单檐蓝瓦攒尖顶、鎏金宝顶、门窗和石栏台基。保留 OSM 位置。其他高度、台阶、雕刻和彩绘为推定，非测绘模型。','detailView':{'label':'走近皇穹宇门窗','x':x,'y':y-.07,'height':.085,'span':.22,'offset':[.01,.035,.27]},'contextView':{'label':'皇穹宇周边','x':x,'y':y-.18,'height':.04,'span':.82,'offset':[45,95,150]},'relatedModels':[{'id':'tiantan','label':'查看祈年殿'},{'id':'tiantan-corridor','label':'查看七十二长廊'}],'lods':{}}
for level in ['preview','detail']:
 a=json.loads((R/f'output/imperial-vault/{level}.json').read_text());s['lods'][level]=f'public/assets/imperial-vault/{level}.glb?v={a["revision"]}'
m['assets']=[a for a in m['assets']if a['id']!=s['id']]+[s]
for a in m['assets']:
 if a['id']=='tiantan':a['relatedModels']=[q for q in a.get('relatedModels',[])if q['id']!=s['id']]+[{'id':s['id'],'label':'查看皇穹宇'}]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2));f=R/'index.html';s=f.read_text().replace('20260930-corridor1','20260930-vault1');note='<h3>皇穹宇</h3><p>依据天坛官网尺寸和实景照片重建单檐蓝瓦攒尖顶与石栏台基；细部为推定。<a href="public/assets/imperial-vault/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in s:s=s.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(s)
(R/'public/assets/imperial-vault/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>皇穹宇模型来源与精度</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:18px/1.8 system-ui;color:#213a32}</style><h1>皇穹宇 · 实景参考重建</h1><p><a href="https://tiantanpark.cn/scenic_spot_list_g7yU_96/detail/1178.html">天坛公园《皇穹宇》</a>：殿台通高19.5米、直径15.6米。本模型采用此尺寸。<a href="https://gygl.beijing.gov.cn/mlgy/mlgy_gyjg01/201912/t20191211_1048216.html">北京市公园管理中心</a>另记通高19.2米，形制为单檐攒尖顶。本模型表现现存单檐形式，并非早期重檐形制。</p><p>参考照片：© Windmemories / Wikimedia Commons，<a href="https://commons.wikimedia.org/wiki/File:2017-05-02_Imperial_Vault_of_Heaven.jpg">2017-05-02 Imperial Vault of Heaven.jpg</a>，<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。照片仅作为形制参考，未将像素用作模型贴图。本项目新模型同样按 CC BY-SA 4.0 提供。</p><p>位置及屋檐范围参考 © OpenStreetMap contributors（ODbL）。屋檐高度、台基、台阶、门窗尺寸、石雕与彩画为推定；饰面使用项目代表性纹理，非文物逐笔还原。两级模型用于旅游地图浏览，非扫描或摄影测量。周边回音壁、配殿和券门已作为独立院落模型接入。东、西、南三向各十四级台阶依据北京市文物局建筑研究；台阶宽度与雕刻仍为推定。</p></html>''')
