import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];p=json.loads((R/'data/echo-court-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text());x,y=p['center'];pts=p['wall'];bounds=[min(t[0]for t in pts)-.01,min(t[1]for t in pts)-.015,max(t[0]for t in pts)+.01,max(t[1]for t in pts)+.01]
s={'id':'echo-court','name':'回音壁院落','subject':'回音壁、东西配殿与三座券门','parentPlace':'tiantan','methodLabel':'实景与文献参考重建','x':x,'y':y,'rotation':0,'bounds':bounds,'maskPolygons':[a['mask']for a in p['parts']],'sourceOsmIds':[a['osmId']for a in p['parts']],'plantingPolygon':p['sourceWall'],'span':.78,'height':.071,'groundHeight':.012,'viewOffset':[35,90,150],'author':'参考摄影：Bjoertvedt、Vmenkov；建筑重建：本项目','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'public/assets/echo-court/ATTRIBUTION.html','method':'依据实景照片和北京市文物局建筑研究重建。回音壁高3.72米、厚0.9米；保留地图轮廓，其直径约67.85米，与文献61.5米存在差异。配殿及券门高度、彩画、门窗和铺装为推定，非测绘实景模型。','detailView':{'label':'走近回音壁券门','x':x,'y':y-.315,'height':.038,'span':.22,'offset':[.015,.045,.14]},'contextView':{'label':'完整院落','x':x,'y':y+.025,'height':.06,'span':.87,'offset':[30,115,145]},'relatedModels':[{'id':'imperial-vault','label':'查看皇穹宇'},{'id':'tiantan','label':'查看祈年殿'}],'lods':{}}
for level in ['preview','detail']:
 a=json.loads((R/f'output/echo-court/{level}.json').read_text());s['lods'][level]=f'public/assets/echo-court/{level}.glb?v={a["revision"]}'
m['assets']=[a for a in m['assets']if a['id']!=s['id']]+[s]
for a in m['assets']:
 if a['id']in ['imperial-vault','tiantan']:a['relatedModels']=[q for q in a.get('relatedModels',[])if q['id']!=s['id']]+[{'id':s['id'],'label':'查看回音壁院落'}]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2))
f=R/'index.html';html=f.read_text().replace('20260930-vault1','20260930-echo1');note='<h3>回音壁院落</h3><p>按实景与文献补建回音壁、配殿和三座券门。<a href="public/assets/echo-court/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in html:html=html.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(html)
(R/'public/assets/echo-court/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>回音壁院落 · 来源与精度</title><style>body{max-width:760px;margin:60px auto;padding:24px;font:18px/1.8 system-ui;color:#213a32}</style><h1>回音壁院落 · 实景与文献参考重建</h1><p>包含回音壁、东配殿、西配殿及南侧三座券门。依据<a href="https://wwj.beijing.gov.cn/bjww/362760/362770/436348561/">北京市文物局《北京天坛圜丘坛建筑尺度研究》</a>：回音壁高3.72米、厚0.9米，蓝琉璃瓦联檐通脊；配殿为歇山顶；皇穹宇东、西、南三向台阶各十四级。</p><p>位置、墙线与建筑占地采用 © OpenStreetMap contributors（ODbL）。地图墙线拟合直径约67.85米，与研究中的现代实测61.5米有差异。本版保留原地图位置和邻接关系，没有将其标称为精确测绘。配殿、券门的高度与装饰、五间立面、台阶尺寸、门扇开启状态和铺装均为推定。</p><h2>照片参考</h2><p>© Bjoertvedt：<a href="https://commons.wikimedia.org/wiki/File:Beijing_-_Temple_of_Heaven_Park_IMG_5012_Echo_Wall_-_Imperial_Vault_of_Heaven.jpg">Echo Wall – Imperial Vault of Heaven</a>，<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。</p><p>© Vmenkov：<a href="https://commons.wikimedia.org/wiki/File:VM_Echo_Wall_gates_4590.jpg">Echo Wall gates</a>，<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>。</p><p>上述照片用于形制参考，未将照片像素制成贴图。新模型按 CC BY-SA 4.0 提供。彩画使用项目代表性纹理，非文物逐笔复原。本模型用于旅游地图浏览，不是摄影测量或点云扫描成果。</p></html>''')
