import json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];p=json.loads((R/'data/qianmen-plan.json').read_text());f=R/'public/assets/route-landmarks/manifest.json';m=json.loads(f.read_text())
for a in p['assets']:
 id=a['id'];x,y=a['center'];gate=id=='qianmen';name='正阳门城楼'if gate else'正阳门箭楼';s={'id':id,'name':name,'subject':'三滴水灰瓦、朱红柱廊与城台券门'if gate else'四层箭窗、白色窗檐与北侧抱厦','methodLabel':'资料与实景参考重建','x':x,'y':y,'rotation':a['angle'],'bounds':a['bounds'],'sourceOsmIds':[a['osmId']],'maskPolygon':a['maskPolygon'],'plantingPolygon':a['plantingPolygon'],'span':1.10 if gate else .88,'height':a['dimensions'][2]/100,'groundHeight':.012,'viewOffset':[40,85,150],'author':'参考摄影：Christophe95、Pixor；建筑重建：本项目','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'public/assets/qianmen-detail/ATTRIBUTION.html','method':'保留 OSM 中心与朝向，按公开尺寸和照片重建。门洞、瓦垄、柱廊及箭窗为几何模型；局部尺寸与装饰为推定，非文物测绘。','detailView':{'label':'走近城楼柱廊'if gate else'走近箭窗与窗檐','x':x,'y':y,'height':.23 if gate else .22,'span':.37 if gate else .43,'offset':[.30,.27,.95]},'contextView':{'label':'正阳门城楼与箭楼','x':(p['assets'][0]['center'][0]+p['assets'][1]['center'][0])/2,'y':(p['assets'][0]['center'][1]+p['assets'][1]['center'][1])/2,'height':.12,'span':2.5,'offset':[35,130,170]},'relatedModels':[{'id':'qianmen-arrow'if gate else'qianmen','label':'查看箭楼'if gate else'查看城楼'}],'lods':{}}
 if not gate:s['parentPlace']='qianmen'
 for level in['preview','detail']:
  a0=json.loads((R/f'output/qianmen-detail/{id}-{level}.json').read_text());s['lods'][level]=f'public/assets/qianmen-detail/{id}-{level}.glb?v={a0["revision"]}'
 # Include projecting access stairs in culling/planting bounds, but mask only
 # the old building footprint so adjacent public ground is not deleted.
 lo,hi=a0['boundsLocal'];co,si=math.cos(a['angle']),math.sin(a['angle'])
 polygon=[[x+xx*co-yy*si,y+xx*si+yy*co]for xx,yy in[(lo[0],lo[1]),(hi[0],lo[1]),(hi[0],hi[1]),(lo[0],hi[1])]]
 s['plantingPolygon']=polygon;s['bounds']=[min(p[0]for p in polygon),min(p[1]for p in polygon),max(p[0]for p in polygon),max(p[1]for p in polygon)]
 m['assets']=[b for b in m['assets']if b['id']!=id]+[s]
f.write_text(json.dumps(m,ensure_ascii=False,indent=2))
f=R/'index.html';t=f.read_text().replace('20260930-atlas4','20260930-qianmen1');note='<h3>正阳门城楼与箭楼</h3><p>三滴水城楼与四层箭窗分别重建，包含瓦垄、柱廊、凹入箭窗和贯通券门。采用公开尺寸与 OSM 位置，细部为推定。<a href="public/assets/qianmen-detail/ATTRIBUTION.html" target="_blank" rel="noreferrer">来源与精度说明</a>。</p>'
if note not in t:t=t.replace('<h3>关于三维地图</h3>',note+'<h3>关于三维地图</h3>')
f.write_text(t)
(R/'public/assets/qianmen-detail/ATTRIBUTION.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>正阳门 · 模型来源与精度</title><style>body{max-width:780px;margin:48px auto;padding:24px;font:18px/1.85 system-ui;color:#273c35}a{color:#246b66}</style><h1>正阳门城楼与箭楼</h1><p>两座独立建筑按地图位置制作远景与近景模型。城楼包含三滴水屋顶、七开间柱廊、菱花格扇、砖砌城台和前后不同截面的券门；箭楼包含四层箭窗、北侧抱厦、白色窗檐与栏杆。没有复建已拆除的瓮城。</p><h2>公开尺寸</h2><p>城楼城台95 × 31.45米、高14.7米，楼身36.7 × 16.5米，通高43.65米；外券宽6米、高6.29米，内券宽7.08米、高9.49米，来自<a href="https://wwj.beijing.gov.cn/bjww/wwjzzcslm/1737418/1738081/gzdt53/10856451/2020082814592768170.pdf">北京市文物局公布的2020年消防工程设计方案评审意见书</a>。不同介绍中的城台高度存在13.2米和14.7米差异，本项目选择上述工程资料。屋顶层间高度及装饰按照片推定，再校准总高；不宣称完整建筑尺寸已得到测绘核验。</p><p>箭楼通高35.37米与灰筒瓦、绿琉璃剪边形制参考<a href="https://www.beijing.gov.cn/renwen/rwzyd/gdwh/zym/202107/t20210706_2430351.html">北京市政府《正阳门》</a>。前楼宽62米、进深20米，北抱厦宽42米、进深12米及箭窗演变依据<a href="https://wwj.beijing.gov.cn/bjww/362760/362770/623138/index.html">北京市文物局《正阳门箭楼箭窗之谜》</a>。模型分别设置南面52孔、主楼东西面32孔、抱厦两侧10孔，加北侧玻璃窗1处。95处包含一扇不属于箭窗的采光窗。窗宽、楼层间距、台阶、北屋面连接和装饰细节为视觉推定。</p><h2>地图与实景</h2><p>两座建筑中心与朝向采用 © OpenStreetMap contributors / ODbL。城楼现有 OSM 轮廓约109.5 × 22米，与公开城台尺寸不一致：模型保留地图中心和朝向，城台采用公开尺寸；旧地图体块按原轮廓遮罩替换，未缩放或移动整个城区。箭楼基台厚度与位置在现有轮廓附近推定。</p><p>参考摄影：© Christophe95，<a href="https://commons.wikimedia.org/wiki/File:Zhengyangmen_gatehouse_1.jpg">Zhengyangmen gatehouse 1</a>、<a href="https://commons.wikimedia.org/wiki/File:Zhengyangmen_archery_tower_1.jpg">archery tower 1</a>、<a href="https://commons.wikimedia.org/wiki/File:Zhengyangmen_archery_tower_2.jpg">archery tower 2</a>，CC BY-SA 4.0（2018）；© Pixor，<a href="https://commons.wikimedia.org/wiki/File:The_Zhengyangmen_archery_tower_from_the_north.jpg">The Zhengyangmen archery tower from the north</a>，CC BY-SA 3.0。照片仅用于形制参考，未将照片像素用作模型贴图。</p><p>新建模型以<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>提供。城砖色差、窗格、脊兽与栏杆是代表性几何重建；彩绘沿用项目生成装饰纹理，匾字为现代字体排版。未模拟内部展陈、实时施工或开放状态。本模型不用于文保测量、修缮或导航入口判断。</p></html>''')
print('Integrated Qianmen pair;',len(m['assets']),'models')
