"""Anchor Beijing Dacheng Hall to its mapped footprint; keep source uncertainty explicit."""
import json, math
from pathlib import Path
R=Path(__file__).resolve().parents[1]
r=next(r for r in json.loads((R/'data/urban/records.json').read_text())['records'] if r['osmId']==227782229)
ring=r['rings'][0];edges=[(a,b,math.dist(a,b))for a,b in zip(ring,ring[1:]+ring[:1])];a,b,_=max(edges,key=lambda e:e[2]);angle=math.atan2(b[1]-a[1],b[0]-a[0]);angle=(angle+math.pi/2)%math.pi-math.pi/2
co,si=math.cos(angle),math.sin(angle);cx,cy=r['center'];local=[[(x-cx)*co*100+(y-cy)*si*100,-(x-cx)*si*100+(y-cy)*co*100]for x,y in ring]
p={'id':'confucius','name':'北京孔庙·大成殿','osmId':r['osmId'],'center':r['center'],'angle':angle,'maskPolygon':ring,'localFootprint':local,'roofWidth':max(v[0]for v in local)-min(v[0]for v in local),'roofDepth':max(v[1]for v in local)-min(v[1]for v in local),'reportedHeight':33,'heightSource':'Beijing Cultural Heritage Bureau published description; not survey verified; photo proportions require review','sources':[{'url':'https://wwj.beijing.gov.cn/bjww/resource/cms/article/362762/515685/2018052316362925466.pdf','role':'official description: nine by five bays, double-eave hipped roof, reported 33 m; search excerpt, PDF fetch pending'},{'url':'https://www.visitbeijing.com.cn/article/47QtU9q713x','role':'nine by five bays and yellow double-eave hipped roof'},{'url':'https://commons.wikimedia.org/wiki/File:Dacheng_Hall,_Beijing_Confucius_Temple_1.jpg','author':'호고호','license':'CC0-1.0','local':'output/confucius-detail/references/front.jpg'},{'url':'https://commons.wikimedia.org/wiki/File:Dacheng_Hall,_Beijing_Confucius_Temple_3.jpg','author':'호고호','license':'CC0-1.0','local':'output/confucius-detail/references/oblique.jpg'}],'limitations':['Photographs obscure outer bays with trees.','No surveyed elevations or hidden rear details.','Do not use Qufu Dacheng Hall dimensions or dragon-column details.']}
(R/'data/confucius-plan.json').write_text(json.dumps(p,ensure_ascii=False,indent=2));print({k:p[k]for k in ['center','angle','roofWidth','roofDepth','reportedHeight']})
